export const gamesList = [
    {
        name: "Ping Pong",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers.jpg",
        price: 35,
        id: "1",
        qty: 0,
    },
    {
        name: "Super Duper",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers2.jpg",
        price: 25,
        id: "2",
        qty: 0,
    },
    {
        name: "Black",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers3.jpg",
        price: 36,
        id: "3",
        qty: 0,
    },
    {
        name: "Furious",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers4.jpg",
        price: 19,
        id: "4",
        qty: 0,
    },
    {
        name: "Assassin",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers5.jpg",
        price: 20,
        id: "5",
        qty: 0,
    },
    {
        name: "Space War",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers6.jpg",
        price: 50,
        id: "6",
        qty: 0,
    },
    {
        name: "Racing",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers7.jpg",
        price: 45,
        id: "7",
        qty: 0,
    },
    {
        name: "Boxer",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers8.jpg",
        price: 35,
        id: "8",
        qty: 0,
    },
    {
        name: "Cyberpunk",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers9.jpg",
        price: 32,
        id: "9",
        qty: 0,
    },
    {
        name: "Forge Legend",
        description: "The critics love it! It's shipped 2 million units in Japan in its first week, where's yours?",
        image: "images/GameHub_covers10.jpg",
        price: 49,
        id: "10",
        qty: 0,
    },
]